# Generated By: Cursor (Claude Sonnet 4.5)
# Build and Distribution Targets
# ================================

.PHONY: build build-wheel

build: requirements-dev ## Build wheel distribution
	@$(VENV_PYTHON) -m build --wheel
	@printf "$(GREEN)✅ Wheel built: dist/metrics_utility-$(VERSION)-py3-none-any.whl$(RESET)\n"

