# Generated By: Cursor (Claude Sonnet 4.5)
# Lint Targets
# =============

.PHONY: lint format

lint: requirements-dev ## Run linting and type checking
	@if [ -f "$(VENV_UV)" ]; then \
		$(VENV_UV) pip install -e . --quiet; \
	else \
		$(VENV_PIP) install -e . --quiet; \
	fi
	@$(VENV_PYTHON) -m ruff check src/ tests/
	@$(VENV_PYTHON) -m mypy src/
	@printf "$(GREEN)✅ Linting complete$(RESET)\n"

format: requirements-dev ## Format code
	@$(VENV_PYTHON) -m ruff format src/ tests/
	@$(VENV_PYTHON) -m ruff check --fix src/ tests/ || true
	@printf "$(GREEN)✅ Code formatted$(RESET)\n"

